### ISSUE TITLE
A few issues here

### ISSUE THREAD

**Issue by nkukarl** [peinanteng/leetcode#40]
https://github.com/peinanteng/leetcode/blob/fe45b660dc2f699611d5ecd46b5a30b0fcecbf0a/groupAnagrams.py#L9

line 9, should not call it `char`, should call it `string` instead (`str` is a reserved word in Python).
line 10, should never call something `temp`...
Maybe should change `summary` to `summaries` on line 8.

And apparently, you don't need line 12 - 14 since in Python 2, you can just do
```
return summaries.values()
```
In Python 3, do
```
return list(summaries.values())
```

And you don't need `self.res`...

**Comment by peinanteng** [comment]
file changed according to the comment. Thanks for the valuable comments.
