### ISSUE TITLE
Try to avoid using `self.res`

### ISSUE THREAD

**Issue by nkukarl** [peinanteng/leetcode#52]
https://github.com/peinanteng/leetcode/blob/b05ea43a8a3193862c5a6a4a3a0da89eab4890b9/permutation.py#L7

Instead of using `self.res`, I guess you can just pass another variable as an array in `self.helper`, which stores the final answer.
Would love to see this implementation.

This comment applies to wherever a `self.XXX` attribute is used.

**Comment by peinanteng** [comment]
Thanks, I will see if I can implement it in a different way.

**Comment by peinanteng** [comment]
Comments have been addressed.
