### ISSUE TITLE
A few issues to solve

### ISSUE THREAD

**Issue by nkukarl** [peinanteng/leetcode#59]
https://github.com/peinanteng/leetcode/blob/e513dd1229611cf2210801efcce4cdcd04956b5b/uniquePathsII.py#L7-L8
Should check the value of `m` and `n` upfront.

https://github.com/peinanteng/leetcode/blob/e513dd1229611cf2210801efcce4cdcd04956b5b/uniquePathsII.py#L11
Should check this before defining `matrix` since this might lead to an early return.

https://github.com/peinanteng/leetcode/blob/e513dd1229611cf2210801efcce4cdcd04956b5b/uniquePathsII.py#L13L24
Why not for-loop?

https://github.com/peinanteng/leetcode/blob/e513dd1229611cf2210801efcce4cdcd04956b5b/uniquePathsII.py#L29
Can do `matrix[-1][-1]`

**Comment by peinanteng** [comment]
The comments have been addressed.
